{% set name = "cryptlib" %}
{% set version = "3.4.8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cryptlib-release.s3-ap-southeast-1.amazonaws.com/{{ name }}{{ version | replace(".", "") }}.zip
  sha256: ba34d50be7061b59d3cd49ff36c6c12603c3e23b9354b61d818ff8fd8843893a
  patches:
    - 0001-Add-missing-include.patch
    - 0002-Use-cf-compiler.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('cryptlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    # Required for sys/auxv.h
    - make
    - sed
  host:
    - zlib

test:
  commands:
    - test -f $PREFIX/lib/libcl.{{ version.split(".")[:2] | join(".") }}.dylib  # [osx]
    - test -f $PREFIX/lib/libcl.so  # [not osx]

about:
  home: https://www.cs.auckland.ac.nz/~pgut001/cryptlib/
  license: Sleepycat
  license_file: COPYING
  summary: "A high-level security interface toolkit providing encryption and authentication"

extra:
  recipe-maintainers:
    - chrisburr
